In [1]:
import numpy as np


In [2]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [3]:
print(v1)
print(v2)


[1 2 3]
[4 5 6]


In [6]:
v_add = v1+v2
v_sup = v1-v2
v_sp = v1*v2
print(v_add)
print(v_sup)
print(v_sp)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [10]:
vscaled = v1*2
print(vscaled)
crossproduct = np.dot(v1,v2)
print(crossproduct)
magnitude = np.linalg.norm(v1)
print(magnitude)

[2 4 6]
32
3.7416573867739413


In [12]:
A= np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]
